### ISSUE TITLE
Project Page does not open

### ISSUE THREAD

**Issue by dwvieira** [NYCPlanning/dcp-zap-data-feedback#87] opened 2018-10-02 14:56 UTC
In the ZAP public portal, the project record for SS SD 115 Canton Avenue does not open. See the attached screenshots.

![ss sd 115 canton ave - 1](https://user-images.githubusercontent.com/22371945/46356915-b8261200-c631-11e8-8c72-4bd231a3c03e.PNG)
![ss sd 115 canton ave - 2](https://user-images.githubusercontent.com/22371945/46356916-b8261200-c631-11e8-80c9-923399f85d7b.PNG)

**Comment by SomeCityBureaucrat** [comment] 2018-10-02 15:01
Hannah, can you look into this?  I don't think it is a data issue.

**Comment by hannahkates** [comment] 2019-04-11 10:01
The problem is that there are 5 projects that all have the same ID (dcp_name) in ZAP. See screenshot below. When the project profile tries to load, it queries for the `2019R0101` ID, expecting to get a single project back. It bugs out when it receives 5 project records instead.

Is the ID incorrect for some of these projects?

![image](https://user-images.githubusercontent.com/13967925/55948490-a778d900-5c1e-11e9-867e-d1c8ccd1b47d.png)

**Comment by dwvieira** [comment] 2019-04-11 13:05
Ahhh now I remember. This was a bug in ZAP with the new 2019 project ids. It kept recreating the same project ids for new project records. We closed the project records, but it seems that they still have a public status of filed. I am going to try to switch the project record to a blank public status to see if it gets removed from the ZAP portal.

**Comment by dwvieira** [comment] 2019-04-12 12:31
Changing the public status to blank seems to have resolved the issue. I think we can close this thread.

**Comment by hannahkates** [comment] 2019-04-12 15:59
Great, thanks for fixing that @dwvieira! Closing the issue.

**Closed as completed by hannahkates** 2019-04-12 15:59 UTC
